name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: docker login
      run: |
        docker login -u praveendevops1337 -p 9ec686ffD@1

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag samplenodejs
      
      
    - name: checking docker images  
      run: docker images
  
    - name: docker tagging image
      run: |
        docker tag samplenodejs:latest praveendevops1337/samplenodejs:latest
        
    - name: pushing docker image to dockerhub
      run: |
        docker push 
   
      
        
      
      
      
